# Generated by Django 5.0.6 on 2024-06-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_usuarios_nombre_alter_usuarios_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contraseña',
        ),
    ]
