# Generated by Django 5.0.6 on 2024-06-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
