# Generated by Django 5.0.6 on 2024-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_delete_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocurso',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
