# Generated by Django 5.0.6 on 2024-06-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_favoritos_usuarios_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(default='temporal', max_length=128, verbose_name='Contraseña'),
        ),
    ]
