# Generated by Django 5.0.6 on 2024-06-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_usuariocurso_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocurso',
            name='favorito',
        ),
    ]
